_target_: src.engines.sr3_diffusion.SR3DiffusionEngine
device: ${device}
denoise_model: ${di:model}
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  _args_:
    - ${di:model_params}
conditional: True
beta_variance_schedule:
  _target_: torch.linspace
  start: 1e-6
  end: 1e-2
  steps: 2_000
loss_fn:
  _target_: torch.nn.MSELoss
  reduction: "mean"