_target_: src.torchmodules.sr3_diffusion.unet_skip.UNetWithSkip
out_channels: 3
inner_channels: 32
channel_multipliers: [1, 2, 4, 8, 8]
resnet_blocks_per_unet_layer: 3
dropout: 0.0
skip_connect_scaling: 0.70710678118 # 1/sqrt(2)
affine_conditional_modulation: False