wandb:
  logger:
    _target_: ignite.contrib.handlers.wandb_logger.WandBLogger
    sync_tensorboard: True
    entity: rcai
    project: diffusion-sr
    tags: ['sr3_diffusion', 'ignite']
  handlers:
    log_files:
      engines: ['trainer']
      log_handler:
        _target_: src.handlers.log_files_wandb.LogFilesToWandb
        files_with_policy:
          "./*": live
          "ckpt/*": live
          ".hydra/*": live
      event:
        _target_: ignite.engine.events.Events.EPOCH_COMPLETED
        once: 2