# @package _global_

# run in experiment mode with:
# `python run.py mode=exp name=experiment_name`

run_mode: experiment

# allows for custom naming of the experiment
name: ???

hydra:
  # sets output paths for all file logs to `logs/experiment/name'
  run:
    dir: logs/experiments/${name}/runs/${root_now:%Y-%m-%d}/${root_now:%H-%M-%S}
  sweep:
    dir: logs/experiments/${name}/multiruns/${root_now:%Y-%m-%d}/${root_now:%H-%M-%S}
    subdir: ${hydra.job.num}
