# @package _global_

defaults:
  - default_run_config
  - _self_
  - mode: default
  - loggers: tensorboard

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# disable python warnings if they annoy you
ignore_warnings: True

# seed for random number generators in pytorch, tensorflow, numpy and python.random
seed: null

# name of the run is accessed by loggers
# should be used along with experiment mode
name: null

# print config
print_config: True

# Global hydra settings
hydra:
  # Bugfix/wandb+joblib: https://github.com/wandb/client/issues/1525 
  # See: https://hydra.cc/docs/next/configure_hydra/job/#hydrajobenv_set
  job:
    env_set:
      WANDB_START_METHOD: "thread"