tqdm_progress_bar:
  handler:
    _target_: ignite.contrib.handlers.tqdm_logger.ProgressBar
  kwargs:
    metric_names: all

loss_running_avg:
  handler:
    _target_: ignite.metrics.RunningAverage
    output_transform: ${eval:"lambda x:x.get('loss')"}
  kwargs:
    name: loss

model_summary:
  handler:
    _target_: src.handlers.print_summary.PrintModelSummary
  kwargs:
    model: ${di:model}